STATUS_INITIALIZED = "initialized"
STATUS_GENERATED = "generated"
STATUS_PARSED = "parsed"
STATUS_TRANSLATED = "translated"
STATUS_VERIFIED = "verified"
STATUS_COMPLETED = "completed"
STATUS_FAILED = "failed"

FAILURE_PARSE = "parse"
FAILURE_TRANSLATION = "translation"
FAILURE_VERIFICATION = "verification"

NORMALIZER_LLM_MODEL = "qwen2.5:14b"
GENERATION_LLM_MODEL = "llama3.1:8b"

NORMALIZER_TEMPERATURE = 0
GENERATION_TEMPERATURE = 0